# Generated by Django 4.2.2 on 2023-07-18 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_reviewrating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewrating",
            name="subject",
        ),
    ]
