# Generated by Django 4.2.2 on 2023-07-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
