# Generated by Django 4.2.2 on 2023-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_variation"),
        ("carts", "0002_cartitem_cart_cartitem_is_active_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
