# Generated by Django 4.2.2 on 2023-07-20 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactus",
            old_name="message",
            new_name="massage",
        ),
    ]
