# Generated by Django 4.2.2 on 2023-07-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_rename_message_contactus_massage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=100)),
                ("massage", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="ContactUs",
        ),
    ]
