# Generated by Django 4.2.2 on 2023-07-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_address_line1_alter_order_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line1",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="district",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
